#!/bin/sh
set -e

##
# variables
localbase=$(realpath "$(dirname "$0")"/../../..)
libexec="${localbase}"/libexec/portzap
sharedir="${localbase}"/share/portzap

##
# functions
# shellcheck source=/dev/null
. "${libexec}"/functions/print.sh

##
# main
src="${sharedir}"/doas.conf
dest="${localbase}"/etc/doas.conf
cat "${src}" |
while read -r line; do
    if grep "${line}" "${dest}" > /dev/null 2>&1; then
	continue
    fi
    cat "${src}" >> "${dest}"
    printok "modified ${dest}"
    break
done
