#!/bin/sh
set -e

##
# variables
user="_portzap"
localbase=$(realpath "$(dirname "$0")"/../../..)
libexec="${localbase}"/libexec/portzap
sharedir="${localbase}"/share/portzap

##
# functions
. "${libexec}"/functions/print.sh

verify_allowfile()
{
    allowfile="/var/cron/allow"
    if [ -e "${allowfile}" ]; then
        if grep -Eqe "^${user}$" "${allowfile}"; then
            printok "${user} found in ${allowfile}"
        else
            printerr "add ${user} to ${allowfile} in order to proceed"
            exit 1
        fi
    else
        printok "${allowfile} not found"
    fi
}

verify_denyfile()
{
    denyfile="/var/cron/deny"
    if [ -e "${denyfile}" ]; then
        if grep -Eqe "^${user}$" "${denyfile}"; then
            printerr "remove ${user} from ${denyfile} in order to proceed"
            exit 1
        else
            printok "${user} not found in ${denyfile}"
        fi
    else
        printok "${denyfile} not found"
    fi
}

install_crontab()
{
    src="${sharedir}/crontab"
    dest="/var/cron/tabs/${user}"
    if [ -e "${dest}" ]; then
        yes | crontab -u "${user}" -r
        printok "crontab removed (${dest})"
    fi
    crontab -u "${user}" "${src}"
    chmod u=rw,g=,o= "${dest}"
    printok "crontab installed (${dest})"
}

##
# main
echo -n "configure portzap to run via cron(8) ? yes or no: "
while read -r r; do
    case "${r}" in
    yes|YES)
        verify_allowfile
        verify_denyfile
        install_crontab
        break
        ;;
    no|NO)
        break
        ;;
    *)
        echo -n "yes or no: "
        ;;
    esac
done
