#!/bin/sh
set -e

##
# variables
localbase=$(realpath "$(dirname "$0")"/../../..)
libexec="${localbase}/libexec/portzap"
sharedir="${localbase}/share/portzap"

##
# functions
. "${libexec}"/functions/print.sh

install_doasconf()
{
    src="${sharedir}/doas.conf"
    dest="${localbase}/etc/doas.conf"
    if grep -Fq "$(cat "${src}")" "${dest}"; then
        printok "doas.conf looks up to date"
    else
        cat "${src}" >> "${dest}"
        printok "${dest} has been updated"
    fi
}

##
# main
install_doasconf
