#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../../..)}
libexec="${localbase}"/libexec/portzap
git="${libexec}"/utils/git/run
repodir=$1
commit=$2

##
# main
cd "${repodir}"
"${git}" diff -l0 --name-only --diff-filter=D "${commit}" "HEAD"
