#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../../..)}
libexec="${localbase}"/libexec/portzap
git=$(which git)
mask=$("${libexec}"/utils/get-umask)

##
# main
doas -n \
     -u _portzap \
     /bin/sh -c "umask ${mask}; ${git} ${*}"
