#!/bin/sh
set -e

#
# globals
#
user="_portzap"
uid=$(id -u "${user}" 2> /dev/null || true)
gid=$(/usr/sbin/pw groupshow "${user}" 2> /dev/null | awk -F: '{print $3}')

#
# main
#
rule="gid=${gid}>uid=${uid},gid=${gid},+gid=${gid};uid=0>uid=${uid},gid=${gid},+gid=${gid}"
echo "${rule}"
