#!/bin/sh
set -e

#
# globals
#
libexec="$(dirname "${0}")"/..
git=$(which git)
mask=$("${libexec}"/scripts/get-default-umask)

#
# main
#
"${libexec}"/scripts/sh -c "umask ${mask}; ${git} -c core.editor=true ${*}"
