#!/bin/sh
set -e

#
# globals
#
libexec="$(dirname "${0}")"/..
git=$(which git)
mask=$("${libexec}"/scripts/get-default-umask)

#
# main
#
umask "${mask}"
"${libexec}"/scripts/mdo "${git}" -c core.editor=true "$@"
