#!/bin/sh
set -e

#
# globals
#
libexec="$(dirname "${0}")"/..
git="${libexec}"/scripts/git
repodir=$1
commit=$2

#
# main
#
cd "${repodir}"
"${git}" diff -l0 --name-status -M -C \
    --diff-filter=AMCRTU \
    "${commit}" "HEAD" \
    | awk '{ if ($1 ~ /^R|C/) { print $3 } else { print $2 } }'
