#!/bin/sh
set -e

##
# variables
libexec="$(dirname "${0}")"/..
git="${libexec}"/scripts/git
repodir=$1
commit=$2

##
# main
cd "${repodir}"
"${git}" diff -l0 --name-only --diff-filter=D "${commit}" "HEAD"
