#!/bin/sh
set -e

#
# globals
#
libexec="$(dirname "${0}")"/..
git="${libexec}"/scripts/git
repodir=$1
commit=$2

#
# main
#
cd "${repodir}"
"${git}" diff -l0 --name-status -M \
    --diff-filter=DR \
    "${commit}" "HEAD" \
    | awk '{ print $2 }'
