#!/bin/sh
set -e

##
# globals
libexec="$(dirname "${0}")"/..
mask=$("${libexec}"/scripts/get-default-umask)

##
# main
install -o root \
        -g _portzap \
        -m "${mask}" \
        -v \
        "${@}"
