#!/bin/sh
set -e

##
# variables
libexec="$(dirname "${0}")"/..
user="_portzap"

##
# functions
# shellcheck source=/dev/null
. "${libexec}"/functions/print.sh

##
# main
if ! id -u "${user}" > /dev/null 2>&1; then
    pw useradd \
       -n "${user}" \
       -c "portzap user" \
       -m \
       -M "$("${libexec}"/scripts/get-default-umask)" \
       -s /sbin/nologin
fi
printok "user setup complete"
