#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/portzap
user="_portzap"

##
# functions
# shellcheck source=/dev/null
. "${libexec}"/functions/print.sh

##
# main
if id -u "${user}" > /dev/null 2>&1; then
   printok "${user} user exists"
else
    pw useradd \
       -n "${user}" \
       -c "portzap user" \
       -m \
       -M $("${libexec}"/scripts/get-default-umask) \
       -s /sbin/nologin
    printok "${user} user created"
fi
