#!/bin/sh
set -e

##
# vars
localbase=$(realpath "$(dirname "$0")"/../../..)
libexec="${localbase}"/libexec/portzap
sharedir="${localbase}"/share/portzap

##
# functions
# shellcheck source=/dev/null
. "${libexec}"/functions/print.sh

##
# main
src="${sharedir}"/doas.conf
dest="${LOCALBASE:-/usr/local}"/etc/doas.conf
# shellcheck disable=SC2002
if [ -e "${dest}" ]; then
    cat "${src}" |
    while read -r line; do
        if grep -q "${line}" "${dest}"; then
            continue
        fi
        cat "${src}" >> "${dest}"
        break
    done
else
    install -m "u=rw,go=" \
            -o root \
            -g wheel \
            "${src}" \
            "${localbase}"/etc
fi
printok "add ${dest} (double check it!)"
