#!/bin/sh
set -e

#
# globals
#
localbase=$(realpath "$(dirname "$0")"/../../..)
libexec="${localbase}"/libexec/portzap
sharedir="${localbase}"/share/portzap

#
# functions
#
# shellcheck source=/dev/null
. "${libexec}"/functions/print.sh

#
# main
#
source="${sharedir}"/doas.conf
destination="${LOCALBASE:-/usr/local}"/etc/doas.conf
# shellcheck disable=SC2002
if [ -e "${destination}" ]; then
    cat "${source}" |
    while read -r line; do
        if grep -q "${line}" "${destination}"; then
            continue
        fi
        cat "${source}" >> "${destination}"
        break
    done
else
    install -m "u=rw,go=" \
            -o root \
            -g wheel \
            "${source}" \
            "${localbase}"/etc
fi
printok "add ${destination}"
