#!/bin/sh
set -e

##
# globals
libexec="$(dirname "${0}")"/..
repodir=$1
installdir=$2
commit=$3

##
# main
cd "${repodir}"
files=$("${libexec}"/scripts/git-get-changed-files "${repodir}" "${commit}")
for file in ${files}; do
    target="${installdir}/${file}"
    parent=$(dirname "${target}")
    parents=""
    while [ ! -e "${parent}" ]; do
        parents="${parent} ${parents}"
        parent=$(dirname "${parent}")
    done
    for dir in ${parents}; do
        "${libexec}"/scripts/install -d "${dir}"
    done
    "${libexec}"/scripts/install "${file}" "${target}"
done
