#!/bin/sh
set -e

##
# variables
libexec="$(dirname "${0}")"/..
repodir=$1
installdir=$2
commit=$3

##
# main
cd "${repodir}"
files=$("${libexec}"/scripts/git-get-removed-files "${repodir}" "${commit}")
for file in ${files}; do
    target="${installdir}"/"${file}"
    parent=$(dirname "${target}")
    echo "rm ${target}"
    rm -f "${target}"
    find "${parent}" -type d -maxdepth 0 -empty -delete
done
