#!/bin/sh -e

##
# variables
localbase=${LOCALBASE:-/usr/local}
git="${localbase}"/bin/git
gitdir=$1
commit=$2

##
# main
cd "${gitdir}"
doas -u _portzap "${git}" diff --name-only --diff-filter=D "${commit}" HEAD
