#!/bin/sh -e

##
# variables
localbase=${LOCALBASE:-/usr/local}
git="${localbase}"/bin/git
gitdir=$1
commit=$2

##
# functions
gitexec()
{
    # shellcheck disable=SC2154
    doas -n -u _portzap \
         /bin/sh -c "umask ${mode}; ${git} ${1}"
}

##
# main
cd "${gitdir}"
gitexec "diff --name-only --diff-filter=D ${commit} HEAD"
