#!/bin/sh -e

##
# variables
gitdir=$1
commit=$2

##
# main
cd "${gitdir}"
add=$(git diff --name-only --diff-filter=A "${commit}" HEAD)
mod=$(git diff --name-only --diff-filter=M "${commit}" HEAD)
echo "${add}"
echo "${mod}"
