#!/bin/sh -e

##
# variables
git=/usr/local/bin/git
gitdir=$1

##
# functions
gitexec()
{
    doas -n -u _portzap \
         /bin/sh -c "umask ${mode}; ${git} ${1}"
}

##
# main
cd "${gitdir}"
gitexec "rev-parse HEAD"
