#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath $(dirname $0)/../..)}
git="${localbase}"/bin/git
gitdir=$1
mode=u=rwX,g=rX,o=

##
# functions
gitexec()
{
    doas -n -u _portzap \
         /bin/sh -c "umask ${mode}; ${git} ${1}"
}

##
# main
cd "${gitdir}"
gitexec "rev-parse HEAD"
