#!/bin/sh
ports_dir=$1
libexec_dir=$2
group=_portzap
mode=u=rwx,g=rwx,o=
for i in $(seq 3 $#); do
    relative_portzap_dir=$(eval echo -n \${$i})
    # Install directory
    install -d -g $group -m $mode \
            $relative_portzap_dir \
            $ports_dir/$relative_portzap_dir
    echo $(realpath $ports_dir/$relative_portzap_dir)

    # Install files
    find $relative_portzap_dir -maxdepth 1 -type f \
        \( -not -name ".gitignore" \) \
        \( -not -name ".arcconfig" \) \
        -exec $libexec_dir/install-file $ports_dir/$relative_portzap_dir {} +

    # Install subdirs (recursive)
    find -s $relative_portzap_dir -depth 1 -type d \
         -exec $libexec_dir/install-directory $ports_dir $libexec_dir {} \;
done
