#!/bin/sh
dest=$1
libexec_dir=$2
group=_portzap
mode=u=rwx,g=rx,o=
for i in $(seq 3 $#); do
    dir=$(eval echo -n \${$i})
    install -d -g $group -m $mode $src $dest/$dir
    echo Install $(realpath $dest/$dir)

    # Install files
    find $dir -maxdepth 1 -type f \
        \( -not -name ".gitignore" \) \
        \( -not -name ".arcconfig" \) \
        -exec $libexec_dir/install-file $dest/$dir {} +

    # Install subdirs (recursive)
    find -s $dir -depth 1 -type d \
        \( -not -name ".git" \) \
        \( -not -name ".hooks" \) \
        -exec $libexec_dir/install-directory $dest $libexec_dir {} \;
done
