#!/bin/sh
src=$1
dest=$2/${src}
mode=$3
libexec_dir=$4
group=_portzap
install_args="-m $mode"

$libexec_dir/install-directory $src $dest
find $src -maxdepth 1 -type f -execdir install $install_args {} $dest/{} \;
if [ -d "$src/files" ];
then
    $libexec_dir/install-directory $src/files $dest/files
    find $src/files -maxdepth 1 -type f -execdir install $install_args {} $dest/files \;
fi
echo Install $(realpath $dest)
