#!/bin/sh -e

##
# variables
giturl=$1
gitdir=$2

##
# main
if [ -e "${gitdir}/.git" ]; then
    echo "${gitdir} already exists."
    echo "Try 'portzap pull' instead."
    exit 1
fi
umask u=rwX,g=rX,o=
set -x
git clone "${giturl}" "${gitdir}"
cd "${gitdir}"
