#!/bin/sh -e

##
# variables
gitdir=$1
branch=$2

##
# main
umask u=rwX,g=rwX,o=
if [ -e "${gitdir}/.git" ]; then
    set -x
    cd "${gitdir}"
    git pull --rebase origin "${branch}"
else
    echo "[-] ${gitdir} is not a valid git repository."
    echo "[-] Try 'portzap clone'"
    exit 1
fi
