#!/bin/sh -e

##
# variables
gitdir=$1
installdir=$2
revfile=$3
artifacts=".git .gitignore .hooks .arcconfig"
libexec=/usr/local/libexec/portzap

##
# functions
perform_update()
{
    rev=$(cat "${revfile}")
    add=$(doas -u _portzap ${libexec}/git-changed-files "${gitdir}" "${rev}")
    del=$(doas -u _portzap ${libexec}/git-removed-files "${gitdir}" "${rev}")
    set -x
    for file in ${del}; do
        target="${installdir}/${file}"
        rm "${target}"
    done
    for file in ${add}; do
        target="${installdir}/${file}"
        parent=$(dirname "${target}")
        if [ ! -e "${parent}" ]; then
            mkdir -p "${parent}"
        fi
        cp "${file}" "${target}"
        chown root:_portzap "${target}"
        chown root:_portzap "${parent}"
    done
}

perform_install()
{
    find -s . \
        -maxdepth 1 \
        -exec cp -Rfv {} "${installdir}" \; \
        -exec chown -R root:_portzap "${installdir}/{}" \;
    for path in ${artifacts}; do
        rm -rf "${installdir:?}/${path}"
    done
}

##
# main
umask u=rwX,g=rwX,o=
cd "${gitdir}"
if [ -e "${revfile}" ]; then
    perform_update
else
    perform_install
fi
doas -u _portzap ${libexec}/git-rev "${gitdir}" > "${revfile}"
