#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../..)}
libexec="${localbase}"/libexec/portzap
git=$(which git)
mode="u=rwX,g=rX,o="
gitdir="$1"
branch="$2"

##
# functions
gitexec()
{
    doas -n -u _portzap \
         /bin/sh -c "umask ${mode}; ${git} ${1}"
}

printerr() {
    "${libexec}"/printerr "$1"
}

##
# main
if [ "$(id -u)" = "0" ]; then
    printerr "you must be a user other than root"
    exit 1
fi

if ! "${libexec}"/isportzap-member > /dev/null 2>&1; then
    printerr "$(id -un) is not a member of _portzap"
    exit 1
fi

if [ ! -e "${gitdir}/.git" ]; then
    printerr "try 'portzap clone' instead"
    exit 1
fi

set -x
cd "${gitdir}"
gitexec "fetch origin"
gitexec "checkout ${branch}" ||
gitexec "checkout -t origin/${branch}"
set +x
printf "current branch: %s\n" "${branch}"
