#!/bin/sh
set -e

##
# variables
libexec=$(dirname "$0")
localbase=${LOCALBASE:-/usr/local}
git="${localbase}"/bin/git
mode="u=rwX,g=rX,o="
gitdir="$1"
branch="$2"

##
# functions
gitexec()
{
    doas -n -u _portzap \
         /bin/sh -c "umask ${mode}; ${git} ${1}"
}

##
# main
if ! "${libexec}"/isportzap-member; then
    echo "[x] This command must be run by a member of the '_portzap' group"
    exit 1
fi

if [ ! -e "${gitdir}/.git" ]; then
    echo "[x] ${gitdir} is not a valid git repository."
    echo "[x] Try: portzap clone"
    exit 1
fi

set -x
cd "${gitdir}"
gitexec "fetch origin"
gitexec "checkout ${branch}" ||
gitexec "checkout -t origin/${branch}"
set +x
printf "current branch: %s\n" "${branch}"
