#!/bin/sh -e

##
# variables
localbase=${LOCALBASE:-/usr/local}
libexec=$(dirname "$0")
git="${localbase}"/bin/git
giturl=$1
gitdir=$2
branch=$3

##
# main
if ! "${libexec}"/isportzap-member; then
    echo "[-] This command must be run by a member of the '_portzap' group"
    exit 1
fi

if [ -e "${gitdir}/.git" ]; then
    echo "[-] ${gitdir} exists."
    echo "[-] Try 'portzap pull'"
    exit 1
fi

set -x
umask u=rwX,g=rwX,o=
doas -u _portzap "${git}" clone "${giturl}" "${gitdir}"
cd "${gitdir}"
doas -u _portzap "${git}" config core.filemode off
set +x +e
echo "[-] Checkout ${branch}"
doas -u _portzap "${git}" checkout -t origin/"${branch}" > /dev/null 2>&1;
echo "[-] Done"
