#!/bin/sh
set -e

##
# variables
libexec=$(dirname "$0")
localbase=${LOCALBASE:-/usr/local}
git="${localbase}"/bin/git
gitdir=$1
mode="u=rwX,g=rX,o="

##
# functions
gitexec()
{
    doas -n -u _portzap \
         /bin/sh -c "umask ${mode}; ${git} ${1}"
}

##
# main
if ! "${libexec}"/isportzap-member; then
    echo "ERR This command must be run by a member of the '_portzap' group"
    exit 1
fi

if [ ! -e "${gitdir}/.git" ]; then
    set +x
    echo "ERR ${gitdir} is not a valid git repository."
    echo "ERR Try 'portzap clone'"
    exit 1
fi

set -x
cd "${gitdir}"
branch=$(gitexec "branch --show-current")
gitexec "pull --rebase origin ${branch}"
