.Dd May 2023
.Dt PORTZAP 8
.Os
.Sh NAME
.Nm portzap
.Nd manages a copy of the hardenedbsd ports tree
.Sh SYNOPSIS
.br
portzap clone
.br
portzap pull
.br
portzap install
.br
portzap erase
.Sh DESCRIPTION
.Nm portzap
manages a copy of the hardenedbsd ports tree.
The copy of the ports tree is maintained by members of
the '_portzap' group, and the copy of the ports tree
can be installed to '/usr/ports' by root.
.Sh EXAMPLES
.sp
.sp
.Nm portzap clone
.br
Clone the hardenedbsd ports tree into /home/_portzap/ports/.
.br
This command is delegated to the '_portzap' user.
.Pp
.Nm portzap pull
.br
Pull updates into /home/_portzap/ports/.
.br
This command is delegated to the '_portzap' user.
.Pp
.Nm portzap install
.br
Install /home/_portzap/ports/ into /usr/ports/.
.br
This command requires root privileges.
.Pp
.Nm portzap erase
.br
Start over: erase /usr/ports/ and /home/_portzap/ports/.
.br
This command requires root privileges.
.br
.Pp
.Pp
.Sh ENVIRONMENT
.sp
.sp
.Nm PORTZAP_GITURL
.br
The URL to a git repository.
.br
Default: https://git.hardenedbsd.org/hardenedbsd/ports.git
.sp
.Nm PORTZAP_BRANCH
.br
The git branch to clone and pull updates from.
.br
Default: hardenedbsd/main
.br
.sp
.Nm PORTZAP_INSTALLDIR
.br
The directory where the ports collection will be installed.
.br
Default: /usr/ports/
.sp
.Sh AUTHORS
The
.Nm portzap
utility and this manual page were written by
0x1eef <0x1eef@protonmail.com>.
