.Dd May 2023
.Dt PORTZAP 8
.Os
.Sh NAME
.Nm portzap
.Nd manages a copy of the hardenedBSD ports tree
.Sh SYNOPSIS
.Nm portzap setup
.Nm portzap teardown
.Nm portzap clone
.Nm portzap pull
.Nm portzap sh
.Nm portzap status
.Nm portzap install
.Nm portzap rm
.Nm portzap apply
.Nm portzap unapply
.Sh DESCRIPTION
.Nm portzap
manages a local copy of the hardenedBSD ports tree with consistent ownership,
a clean separation between delegated and root-only operations, and a simple
update/install workflow.
.Sh DEPENDENCIES
The mac_do(4) policy must be loaded into the kernel before portzap(8)
can use mdo(1). To load mac_do(4) at boot time, add the following to
/boot/loader.conf and reboot:
.Bd -literal -offset indent
mac_do_load="YES"
.Ed
.Pp
To load mac_do(4) without a reboot:
.Bd -literal -offset indent
kldload mac_do
.Ed
.Sh SETUP
.sp
.sp
.Nm portzap setup
.br
Setup portzap for the first time
.br
This command requires root privileges
.Pp
.Nm portzap teardown
.br
Reverse the changes made by 'portzap setup'
.br
This command requires root privileges
.Pp
.Nm pw groupmod _portzap -m <user>
.br
Append a user to the '_portzap' group
.br
This command requires root privileges
.Pp
.Sh GENERAL
.sp
.sp
.Nm portzap clone
.br
Clone the hardenedBSD ports tree into /home/_portzap/ports/
.br
This command is delegated to the '_portzap' user and access is controlled
by mac_do(4) rules installed by
.Nm portzap apply
.Pp
.Nm portzap pull
.br
Pull updates into /home/_portzap/ports/
.br
This command is delegated to the '_portzap' user and access is controlled
by mac_do(4) rules installed by
.Nm portzap apply
.br
.Pp
.Nm portzap sh
.br
Run /bin/sh within /home/_portzap/ports/
.br
This command is delegated to the '_portzap' user and access is controlled
by mac_do(4) rules installed by
.Nm portzap apply
.Pp
.Nm portzap status
.br
Report whether mac_do(4) rules for portzap are applied
.br
This command can be run by any user
.Pp
.Nm portzap rm
.br
Remove the contents of /usr/ports/ and /home/_portzap/ports/
.br
This command requires root privileges
.Pp
.Nm portzap install
.br
Install /home/_portzap/ports/ into /usr/ports/
.br
This command requires root privileges
.br
.Pp
.Nm portzap apply
.br
Apply mac_do(4) rules
.br
This command requires root privileges
.Pp
.Nm portzap unapply
.br
Remove mac_do(4) rules
.br
This command requires root privileges
.Sh ENVIRONMENT
.sp
.sp
.Nm PORTZAP_CLONEURL
.br
The URL of a git repository
.br
Default: https://github.com/hardenedBSD/ports
.sp
.Nm PORTZAP_INSTALLDIR
.br
The directory where the ports collection will be installed
.br
Default: /usr/ports/
.sp
.Sh AUTHORS
The
.Nm portzap
utility and this manual page were written by
0x1eef <0x1eef@protonmail.com>.
