.Dd May 2023
.Dt PORTZAP 8
.Os
.Sh NAME
.Nm portzap
.Nd manages a copy of the hardenedbsd ports tree
.Sh SYNOPSIS
.br
portzap clone
.br
portzap pull
.br
portzap install
.Sh DESCRIPTION
.Nm portzap
manages a copy of the hardenedbsd ports tree.
.Sh EXAMPLES
.Pp
.Nm portzap clone
.br
Clone the hardenedbsd ports tree into /home/_portzap/ports/.
.Pp
.Nm portzap pull
.br
Pull updates into /home/_portzap/ports/.
.Pp
.Nm portzap install
.br
Install /home/_portzap/ports/ into /usr/ports/.
.Sh ENVIRONMENT VARIABLES
.Pp
.Bl -tag -width $PORTZAP_PORTS_URL
.It Ev PORTZAP_PORTS_URL
The URL to a git repository.
Default: https://git.hardenedbsd.org/hardenedbsd/ports.git
.It Ev PORTZAP_PORTS_DIR
The directory where the ports collection will be installed. Default: /usr/ports/.
.Sh AUTHORS
The
.Nm portzap
utility and this manual page were written by
0x1eef <0x1eef@protonmail.com>.
