#!/bin/sh
set -e

#
# globals
#
libexec="$(dirname "${0}")"/..
git="${libexec}"/scripts/git
repourl=$1
repodir=$2
branch=$3

#
# functions
#
. "${libexec}"/functions/print.sh

#
# main
#
if [ -e "${repodir}"/.git ]; then
    printerr "repository has already been cloned"
    exit 1
fi

"${git}" clone "${repourl}" "${repodir}"
cd "${repodir}"
"${git}" config core.filemode off
"${git}" checkout -t origin/"${branch}" > /dev/null 2>&1 || true
printok "clone complete"
