#!/bin/sh
set -e

##
# vars
libexec="$(dirname "${0}")"/..
repodir=$1
installdir=$2

##
# functions
# shellcheck source=/dev/null
. "${libexec}"/functions/print.sh

erase()
{
    # shellcheck disable=SC3043
    local dir
    dir="${1}"
    printf "%s  " "${dir}"
    find "${dir}" \
         -maxdepth 1 \
         \! -name "." \
         \! -name ".." \
         \! -name "ports" \
         -exec printf . \; \
         -exec rm -rf "{}" \;
    echo
}

##
# main
if [ "$(id -u)" != "0" ]; then
    printerr "you must be root"
    exit 1
fi

printf "1 Remove the contents of %s\n" "${repodir}"
printf "2 Remove the contents of %s\n" "${installdir}"
printf "3 Remove the contents of both (%s and %s)\n" "${repodir}" "${installdir}"
printf "4 Do nothing\n"
printf "1-4: "
while true; do
    read -r r
    if [ "${r}" = "1" ]; then
        erase "${repodir}"
        printok "remove complete"
    elif [ "${r}" = "2" ]; then
        erase "${installdir}"
        printok "remove complete"
    elif [ "${r}" = "3" ]; then
        erase "${repodir}"
        erase "${installdir}"
        printok "remove complete"
    elif [ "${r}" = "4" ]; then
        break
    else
        printf "%s is not a valid option\n" "${r}"
        printf "1-4: "
        continue
    fi
    exit
done
