#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/portzap
git="${libexec}"/utils/git/run
gitdir=$1
installdir=$2
revfile=$3

##
# functions
# shellcheck source=/dev/null
. "${libexec}"/functions/print.sh

##
# main
if [ "$(id -u)" != "0" ]; then
    printerr "you must be root"
    exit 1
fi

cd "${gitdir}"
if [ -e "${revfile}" ]; then
    ##
    # install update
    rev=$(cat "${revfile}")
    "${libexec}"/utils/install/run -d "${installdir}"
    "${libexec}"/utils/install/update-deleted-files "${gitdir}" "${installdir}" "${rev}"
    "${libexec}"/utils/install/update-changed-files "${gitdir}" "${installdir}" "${rev}"
else
    ##
    # install from scratch
    umask u=rwX,g=rX,o=
    "${libexec}"/utils/install/run -d "${installdir}"
    find -s . \
         -maxdepth 1 \
         ! -name "." \
         ! -name ".git" \
         ! -name ".github" \
         ! -name ".gitignore" \
         ! -name ".gitattributes" \
         ! -name ".git-blame-ignore-revs" \
         ! -name ".cirrus-ci" \
         ! -name ".cirrus.yml" \
         ! -name ".gitignore" \
         ! -name ".arclint" \
         ! -name ".arcconfig" \
         -exec cp -Rpv {} "${installdir}" \;
    chown -Rv root "${installdir}"
fi
"${git}" rev-parse HEAD > "${revfile}"
printok "install complete"
