#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/portzap
git="${libexec}"/utils/git/run
repourl=$1
repodir=$2
branch=$3

##
# functions
# shellcheck source=/dev/null
. "${libexec}"/functions/print.sh

##
# main
if [ "$(id -u)" = "0" ]; then
    printerr "you must be a user other than root"
    exit 1
fi

if ! "${libexec}"/utils/isportzap-member; then
    printerr "$(id -un) is not a member of _portzap"
    exit 1
fi

if [ -e "${repodir}/.git" ]; then
    printerr "try 'portzap pull' instead"
    exit 1
fi

"${git}" clone "${repourl}" "${repodir}"
cd "${repodir}"
"${git}" config core.filemode off
"${git}" checkout -t origin/"${branch}" > /dev/null 2>&1 || true
printok "clone complete"
