#!/bin/sh
set -e

#
# globals
#
libexec="$(dirname "${0}")"/..
repodir="${1}"

#
# functions
#
. "${libexec}"/functions/print.sh

#
# main
#
if [ "$(id -u)" = "0" ]; then
    printerr "you must be a user other than root"
    exit 1
fi
if ! "${libexec}"/scripts/is-portzap-member; then
   printerr "$(id -un) is not a member of _portzap"
   exit 1
fi
if [ ! -e "${repodir}" ]; then
    printerr "try 'portzap clone' instead"
    exit 1
fi

cd "${repodir}"
"${libexec}"/scripts/sh
