#!/bin/sh
set -e

#
# globals
#
libexec="$(dirname "$0")"/..

#
# functions
#
. "${libexec}"/functions/print.sh

get_portzap_rules()
{
    "${libexec}"/scripts/get-mdo-rule | tr ';' '\n' | sed '/^$/d'
}

get_system_rules()
{
    sysctl -n security.mac.do.rules 2> /dev/null || true
}

is_rule_enabled()
{
    local syslist
    local entry
    syslist=$(printf "%s" "${1}" | tr ';' '\n')
    while IFS= read -r entry; do
        [ -z "${entry}" ] && continue
        printf "%s\n" "${syslist}" | grep -Fxq -- "${entry}" || return 1
    done <<EOFRULES
${2}
EOFRULES
    return 0
}

#
# main
#
portzap_rules=$(get_portzap_rules)
system_rules=$(get_system_rules)
if [ -z "${system_rules}" ]; then
    printok "disabled"
    exit 1
fi
if is_rule_enabled "${system_rules}" "${portzap_rules}"; then
    printok "enabled"
    exit 0
fi

printok "disabled"
exit 1
