#!/bin/sh
set -e

#
# globals
#
libexec="$(dirname "${0}")"/..
user="_portzap"
uid=$(id -u "${user}" 2> /dev/null || true)
gid=$(pw groupshow "${user}" 2> /dev/null | awk -F: '{print $3}')

#
# functions
#
. "${libexec}"/functions/print.sh
. "${libexec}"/functions/mdo.sh

#
# guards
#
if [ "$(id -u)" != "0" ]; then
    printerr "you must be root"
    exit 1
fi
if [ -z "${uid}" ]; then
    printerr "user ${user} not found"
    exit 1
fi
if [ -z "${gid}" ]; then
    printerr "group ${user} not found"
    exit 1
fi

#
# main
#
portzap_rules=$(get_portzap_rules "${libexec}" | paste -sd ';' -)
system_rules=$(get_system_rules)
merged=$(merge_rules "${system_rules}" "${portzap_rules}")
if [ "${merged}" = "${system_rules}" ]; then
    printok "security.mac.do.rules unchanged"
    exit 0
fi
sysctl security.mac.do.rules="${merged}"
printok "add security.mac.do.rules"
