#!/bin/sh

portzap_clone() {
    portzap_dir=$1
    ports_url=$2
    clone_mask=$3

    if [ -e "$portzap_dir/.git" ]; then
        echo "$portzap_dir exists."
        echo "Run 'portzap pull' instead."
        exit 1
    fi
    umask "$clone_mask"
    git clone "$ports_url" "$portzap_dir"
}
