#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/portzap
git="${libexec}"/utils/git/run
repodir=$1
branch=$2

##
# functions
# shellcheck source=/dev/null
. "${libexec}"/functions/print.sh

##
# main
if [ "$(id -u)" = "0" ]; then
    printerr "you must be a user other than root"
    exit 1
fi

if ! "${libexec}"/utils/isportzap-member; then
    printerr "$(id -un) is not a member of _portzap"
    exit 1
fi

if [ ! -e "${repodir}/.git" ]; then
    printerr "try 'portzap clone' instead"
    exit 1
fi

cd "${repodir}"
"${git}" fetch origin
"${git}" checkout "${branch}" ||
"${git}" checkout -t origin/"${branch}"
printok "checkout complete"
