#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/portzap

##
# functions
# shellcheck source=/dev/null
. "${libexec}"/functions/print.sh

##
# main
if [ "$(id -u)" = "0" ]; then
    "${libexec}"/scripts/setup-user
    "${libexec}"/scripts/setup-doas
    printok "setup complete"
else
    printerr "you must be root"
    exit 1
fi
