#!/bin/sh
set -e

#
# globals
#
libexec="$(dirname "${0}")"/..
repodir="${1}"

#
# functions
#
. "${libexec}"/functions/print.sh

#
# main
#
if [ ! -e "${repodir}" ]; then
    printerr "try 'portzap clone' instead"
    exit 1
fi

cd "${repodir}"
"${libexec}"/scripts/sh
