#!/bin/sh
set -e

#
# globals
#
libexec="$(dirname "${0}")"/..
user=_portzap

#
# functions
#
# shellcheck source=/dev/null
. "${libexec}"/functions/print.sh

#
# main
#
if [ "$(id -u)" = "0" ]; then
    pw userdel  -n "${user}"  > /dev/null 2>&1 || true
    pw groupdel -n "${user}"  > /dev/null 2>&1 || true
    rm -rf /home/"${user:?}"/ > /dev/null 2>&1 || true
    printok "teardown complete"
else
    printerr "you must be root"
    exit 1
fi
