#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/portzap
gitdir=$1

##
# functions
git()
{
    "${libexec}"/utils/git "${@}"
}

printok() {
    "${libexec}"/utils/printok "${1}"
}

printerr() {
    "${libexec}"/utils/printerr "${1}"
}

##
# main
if [ "$(id -u)" = "0" ]; then
    printerr "you must be a user other than root"
    exit 1
fi

if ! "${libexec}"/utils/isportzap-member > /dev/null 2>&1; then
    printerr "$(id -un) is not a member of _portzap"
    exit 1
fi

if [ ! -e "${gitdir}/.git" ]; then
    printerr "try 'portzap clone' instead"
    exit 1
fi

cd "${gitdir}"
branch=$(gitexec "branch --show-current")
gitexec "pull --rebase origin ${branch}"
printok "pull complete"
