#!/bin/sh
set -e

#
# globals
#
libexec="$(dirname "${0}")"/..
git="${libexec}"/scripts/git
repodir=$1
installdir=$2
commitfile=$3

#
# functions
#
. "${libexec}"/functions/print.sh

#
# main
#
if [ "$(id -u)" != "0" ]; then
    printerr "you must be root"
    exit 1
fi

cd "${repodir}"
mkdir -p "${installdir}"
rsync -av \
      --chown=root:_portzap \
      --delete \
      --delete-excluded \
      --exclude=".git" \
      --exclude=".github" \
      --exclude=".gitignore" \
      --exclude=".gitattributes" \
      --exclude=".git-blame-ignore-revs" \
      --exclude=".cirrus-ci" \
      --exclude=".cirrus.yml" \
      --exclude=".arclint" \
      --exclude=".arcconfig" \
      --exclude=".portzap" \
      "${repodir}/" \
      "${installdir}/"
"${git}" rev-parse HEAD > "${commitfile}"
printok "install complete"
