#!/bin/sh
set -e

##
# vars
libexec="$(dirname "${0}")"/..

##
# functions
# shellcheck source=/dev/null
. "${libexec}"/functions/print.sh

##
# main
if [ "$(id -u)" = "0" ]; then
    "${libexec}"/scripts/setup-user
    "${libexec}"/scripts/setup-doas
    printok "setup complete"
else
    printerr "you must be root"
    exit 1
fi
