#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/portzap
mode=u=rwX,g=rX,o=
git="${libexec}"/utils/git/run
gitdir=$1
installdir=$2
revfile=$3

##
# functions
perform_update()
{
    rev=$(cat "${revfile}")
    add=$("${libexec}"/utils/git/get-changed-files "${gitdir}" "${rev}")
    del=$("${libexec}"/utils/git/get-removed-files "${gitdir}" "${rev}")
    for file in ${del}; do
        target="${installdir}/${file}"
        parent=$(dirname "${target}")
        echo "rm ${target}"
        rm -f "${target}"
        find "${parent}" -type d -maxdepth 0 -empty -delete
    done
    for file in ${add}; do
        target="${installdir}/${file}"
        parent=$(dirname "${target}")
        parents=""
        while [ ! -e "${parent}" ]; do
            parents="${parent} ${parents}"
            parent=$(dirname "${parent}")
        done
        for dir in ${parents}; do
            run_install "-d" "${dir}"
        done
        run_install "${file}" "${target}"
    done
}

perform_install()
{
    find -s . \
        -maxdepth 1 \
        ! -name "." \
        ! -name ".git" \
        ! -name ".gitignore" \
        ! -name ".hooks" \
        ! -name ".arcconfig" \
        -exec cp -Rpv {} "${installdir}" \;
    chown -Rv root "${installdir}"
}

run_install()
{
    install -o root -g _portzap -m "${mode}" -v "${@}"
}

printok() {
    "${libexec}"/utils/printok "${1}"
}

printerr() {
    "${libexec}"/utils/printerr "${1}"
}

##
# main
if [ "$(id -u)" != "0" ]; then
    printerr "you must be root"
    exit 1
fi

umask "${mode}"
cd "${gitdir}"
run_install "-d" "${installdir}"
chmod ${mode} "${installdir}"
if [ -e "${revfile}" ]; then
    perform_update
else
    perform_install
fi
"${git}" rev-parse HEAD > "${revfile}"
printok "install complete"
