#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/../../..)}
libexec="${localbase}"/libexec/portzap
gitdir=$1

##
# functions
gitexec()
{
    "${libexec}"/utils/gitexec "${1}"
}

##
# main
cd "${gitdir}"
gitexec "rev-parse HEAD"
