#!/bin/sh
set -e

##
# variables
git=$(which git)
mode=u=rwX,g=rX,o=
gitdir=$1
commit=$2

##
# functions
gitexec()
{
    doas -n -u _portzap \
         /bin/sh -c "umask ${mode}; ${git} ${1}"
}

##
# main
cd "${gitdir}"
gitexec "diff --name-only --diff-filter=D ${commit} HEAD"
